
// AUTHENTICATION
export const RESET_AUTHENTICATION_DATA = 'RESET_AUTHENTICATION_DATA'
export const CHANGE_AUTHENTICATION_DATA = 'CHANGE_AUTHENTICATION_DATA'
export const CHANGE_AUTHENTICATION_MODE = 'CHANGE_AUTHENTICATION_MODE'
export const REMOVE_AUTH_ERROR_ON_FOCUS = 'REMOVE_AUTH_ERROR_ON_FOCUS'

// USERS
export const LOGIN_USER = 'LOGIN_USER'
export const UPLOAD_IMAGE = 'UPLOAD_IMAGE'
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA'
export const RESET_USER_STATE = 'RESET_USER_STATE'
export const CHANGE_USER_DATA = 'CHANGE_USER_DATA'
export const REGISTER_NEW_USER = 'REGISTER_NEW_USER'
export const CHANGE_USER_ADDRESS = 'CHANGE_USER_ADDRESS'
export const REMOVE_USER_ERROR_ON_FOCUS = 'REMOVE_USER_ERROR_ON_FOCUS'